### ISSUE TITLE
Cannot install the cause 

### ISSUE THREAD

**Issue by whecrane** [jean997/cause#11]
Hi Jean,
    I try to install the package used the code : devtools::install_github("jean997/cause@v1.2.0") and the develpment vesion (devtools::install_github("jean997/cause"), neither failed. They got the same error:
* installing *source* package ‘cause’ ...
** using staged installation
** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/include" -DNDEBUG  -I'/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/library/Rcpp/include' -I'/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/library/RcppParallel/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -I/media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/include" -DNDEBUG  -I'/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/library/Rcpp/include' -I'/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/library/RcppParallel/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -I/media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix  -c log_likelihood_functions.cpp -o log_likelihood_functions.o
/bin/sh: -c: row 1 : Syntax error: “(” unexpected
/bin/sh: -c: row 1: `  echo x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -L"/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/lib" -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -L/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -o cause.so RcppExports.o log_likelihood_functions.o     File /media/EXTend2018/Wanghe2019/.Renviron contains invalid line(s)       eb140cdd9ca9cc5901d    They were ignored  -L"/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/lib" -lR; \'
make: *** [/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/share/make/shlib.mk:6: cause.so] Error 1
ERROR: compilation failed for package ‘cause’
* removing ‘/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/R/library/cause’

That will be so nice if you can give me some help. Thank you!

Best wishes, 
Crane

**Comment by jean997** [comment]
Wow I've never seen anything like this error before. My guess is that it is something to do with your conda environment and compiling the c++ code. I will see if I can figure it out. Does it install outside of the conda environment?

**Comment by whecrane** [comment]
I installed it in the conda environment, the version of R is 4.0.




| |
王鹤
|
|
邮箱：whe930102@163.com
|
On 12/05/2020 00:15, Jean Morrison wrote:

Wow I've never seen anything like this error before. My guess is that it is something to do with your conda environment and compiling the c++ code. I will see if I can figure it out. Does it install outside of the conda environment?

**Comment by CreRecombinase** [comment]
Can you post the output of the R command `sessionInfo()`?

**Comment by CreRecombinase** [comment]
Please also post the output of the shell command `R CMD config --all`

**Comment by whecrane** [comment]
This is the outputs:
$R CMD config --all
CC = x86_64-conda_cos6-linux-gnu-cc
CFLAGS = -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
CPICFLAGS = -fpic
CPPFLAGS = -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -I/media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib
CXX = x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
CXXFLAGS = -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
CXXPICFLAGS = -fpic
CXX11 = x86_64-conda_cos6-linux-gnu-c++
CXX11STD = -std=gnu++11
CXX11FLAGS = -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
CXX11PICFLAGS = -fpic
CXX14 = x86_64-conda_cos6-linux-gnu-c++
CXX14STD = -std=gnu++14
CXX14FLAGS = -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
CXX14PICFLAGS = -fpic
CXX17 = x86_64-conda_cos6-linux-gnu-c++
CXX17STD = -std=gnu++17
CXX17FLAGS = -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
CXX17PICFLAGS = -fpic
CXX20 =
CXX20STD =
CXX20FLAGS =
CXX20PICFLAGS =
DYLIB_EXT = .so
DYLIB_LD = x86_64-conda_cos6-linux-gnu-cc
DYLIB_LDFLAGS = -shared -fopenmp
FC = x86_64-conda_cos6-linux-gnu-gfortran
FFLAGS = -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
FPICFLAGS = -fpic
FLIBS = -lgfortran -lm -lgomp -lquadmath -lpthread
FCFLAGS = -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix
SAFE_FFLAGS = -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1591949865905/work=/usr/local/src/conda/r-base-4.0.1 -fdebug-prefix-map=/media/EXTend2018/Wanghe2019/.conda/envs/r_4=/usr/local/src/conda-prefix -msse2 -mfpmath=sse
OBJC = x86_64-conda_cos6-linux-gnu-cc
OBJCFLAGS = -g -O2 -fobjc-exceptions
JAVA = /media/EXTend2018/Wanghe2019/miniconda3/bin/java
JAVAC = /media/EXTend2018/Wanghe2019/miniconda3/bin/javac
JAVAH = /media/EXTend2018/Wanghe2019/miniconda3/bin/javah
JAR = /media/EXTend2018/Wanghe2019/miniconda3/bin/jar
JAVA_HOME = /media/EXTend2018/Wanghe2019/miniconda3/jre
JAVA_LIBS = -L/media/EXTend2018/Wanghe2019/miniconda3/jre/lib/amd64/server -ljvm
JAVA_CPPFLAGS = -I/media/EXTend2018/Wanghe2019/miniconda3/jre/../include -I/media/EXTend2018/Wanghe2019/miniconda3/jre/../include/linux
LDFLAGS = -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -L/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -Wl,-rpath-link,/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib
SHLIB_CFLAGS =
SHLIB_CXXFLAGS =
SHLIB_CXXLD = x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
SHLIB_CXXLDFLAGS = -shared
SHLIB_CXX11LD = x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11
SHLIB_CXX11LDFLAGS = -shared
SHLIB_CXX14LD = x86_64-conda_cos6-linux-gnu-c++ -std=gnu++14
SHLIB_CXX14LDFLAGS = -shared
SHLIB_CXX17LD = x86_64-conda_cos6-linux-gnu-c++ -std=gnu++17
SHLIB_CXX17LDFLAGS = -shared
SHLIB_CXX20LD =
SHLIB_CXX20LDFLAGS = -shared
SHLIB_EXT = .so
SHLIB_FFLAGS =
SHLIB_LD = x86_64-conda_cos6-linux-gnu-cc
SHLIB_LDFLAGS = -shared
TCLTK_CPPFLAGS = -I/media/EXTend2018/Wanghe2019/.conda/envs/r_4/include -I/media/EXTend2018/Wanghe2019/.conda/envs/r_4/include
TCLTK_LIBS = -L/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -ltcl8.6 -L/media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib -ltk8.6 -lX11
BLAS_LIBS = -lblas
LAPACK_LIBS = -llapack
MAKE = make
LIBnn = lib
AR = x86_64-conda_cos6-linux-gnu-ar
RANLIB = x86_64-conda_cos6-linux-gnu-ranlib
## The following variables are deprecated
CPP = /media/EXTend2018/Wanghe2019/.conda/envs/r_4/bin/x86_64-conda_cos6-linux-gnu-cpp
CXXCPP = x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -E

> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /media/EXTend2018/Wanghe2019/.conda/envs/r_4/lib/libopenblasp-r0.3.10.so

locale:
[1] LC_CTYPE=zh_CN.UTF-8 LC_NUMERIC=C
[3] LC_TIME=zh_CN.UTF-8 LC_COLLATE=zh_CN.UTF-8
[5] LC_MONETARY=zh_CN.UTF-8 LC_MESSAGES=zh_CN.UTF-8
[7] LC_PAPER=zh_CN.UTF-8 LC_NAME=C
[9] LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats graphics grDevices utils datasets methods base

loaded via a namespace (and not attached):
[1] compiler_4.0.1

Best wishes,
Crane



在 2020-12-05 00:53:59，"Nicholas Knoblauch" <notifications@github.com> 写道：

Please also post the output of the shell command R CMD config --all

**Comment by CreRecombinase** [comment]
My best guess is that there's something missing from your conda environment, which isn't allowing you to build packages from source.  Can you verify that you are able to install _any_ packages from source?  What happens if you try, for example, `devtools::install_github("dangerzig/tipitaka")`?  Could you also try removing the conda environment and reinstalling it?

**Comment by whecrane** [comment]
Thank you for your help. I used another conda environment and it worked. You are so nice, thanks!





| |
王鹤
|
|
邮箱：whe930102@163.com
|
On 12/05/2020 05:17, Nicholas Knoblauch wrote:

My best guess is that there's something missing from your conda environment, which isn't allowing you to build packages from source. Can you verify that you are able to install any packages from source? What happens if you try, for example, devtools::install_github("dangerzig/tipitaka")? Could you also try removing the conda environment and reinstalling it?
