### ISSUE TITLE
Issues when installing cause with Rv.3.6.

### ISSUE THREAD

**Issue by AlexHatoum** [jean997/cause#14]
Hi! 

This package looks really interesting and I am hoping to test it out. Unfortunately, I run into an error that may be specific to v.3.6 of R but thought I would post here. After downloading and updating packages I get the error and warnings: 

Error: Failed to install 'cause' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1

So I can't download the package. Perhaps there is a quick fix?

Thanks,

Alex Hatoum

**Comment by jean997** [comment]
Hi Alex,
I don't think its an issue with 3.6, I just successfully installed it in both 3.6.1 and 3.6.3. Googling the error has suggested that restarting R may be the solution. Perhaps try that and see if it works.
Jean

**Comment by AlexHatoum** [comment]
So that potentially helps but then the program doesn't update. The issue was that I had two devtools installed packages and they were calling different versions of their dependencies.  So when I update package as I install everything broke. Only having one at a time fixed the issue.
