### ISSUE TITLE
readRDS error

### ISSUE THREAD

**Issue by Carlos-Chau** [jean997/cause#15]
Hi, all RDS files in your tutorial failed to be read by my R-4.0.3 nor R-3.6.3
Would you mind sharing the data structure of `top_vars` please? Thanks

```R
dir.create("example_data")
download.file("https://github.com/jean997/cause/blob/master/example_data/top_ldl_pruned_vars.RDS", destfile = "example_data/top_ldl_pruned_vars.RDS")

top_vars <- readRDS("example_data/top_ldl_pruned_vars.RDS")
res <- cause(X=X, variants = top_vars, param_ests = params)
# Error in readRDS("example_data/top_ldl_pruned_vars.RDS") : 
#  unknown input format
```

**Comment by Carlos-Chau** [comment]
Solved by:
1. git clone this repo
2. Read the RDS file of the repo (as opposed to direct download instructed in the [tutorial](https://jean997.github.io/cause/ldl_cad.html)

**Comment by jean997** [comment]
You can solve this issue without cloning the repo by replacing "blob" in your url with "raw" eg

download.file("https://github.com/jean997/cause/raw/master/example_data/top_ldl_pruned_vars.RDS", destfile = "example_data/top_ldl_pruned_vars.RDS")
