### ISSUE TITLE
pvals_col option still missing after I update?

### ISSUE THREAD

**Issue by sarahcolbert** [jean997/cause#20]
Hi,

I tried to use the pvals_col option and when I noticed that it wasn't working, I tried to re-install the latest version of CAUSE. However, I am still not able to use the option. Could you specify which version is updated with this option so I can make sure I am installing the correct one?

Thanks!

Sarah

**Comment by jean997** [comment]
Hi Sarah -- The `pval_cols` option is new in version 1.2.0.0320. Let me know if you still have trouble after updating.
Jean

**Comment by sarahcolbert** [comment]
That worked! Thanks, Jean!
