### ISSUE TITLE
How many SNPs is enough for est_cause_params? 

### ISSUE THREAD

**Issue by daveipart** [jean997/cause#22]
Hi, 

I am conducting CAUSE analysis between a large number of traits(thousands of combinations), thus the speed of the analysis is very important. Generally, is the 1 million random sampled SNPs enough for the est_cause_params function? How many SNPs do I need to get relatively accurate estimates? I tried to include all SNPs(~ 5 million SNPs) and it is somewhat slow.

Zicheng

**Comment by jean997** [comment]
Hi Zicheng,
For parameter estimation, 1 million has worked well for us. That usually takes something like 2-8 minutes. For estimating posteriors, I usually use a threshold of p < 0.001 for the exposure. I think you will get a warning if you use something larger. Typically this is around 1-3k SNPs and doesn't usually take very long. Don't forget to prune for LD, that step is important. 

A few days ago I made a small change that should speed up the posterior fitting step in some situations. You can try the latest version and see if that is faster. 

Jean

**Comment by msolerartigas** [comment]
Hi Jean,

Is LD pruning required as well for the  parameter estimation step (est_cause_params) or just for fitting the model (cause)?

Thanks!
María

**Comment by jean997** [comment]
LD pruning is only required for model fitting. We found it didn't make a
difference for parameter estimation and you can lose accuracy due to having
fewer SNPs.
