### ISSUE TITLE
heritability filter?

### ISSUE THREAD

**Issue by msolerartigas** [jean997/cause#23]
Hi,

First of all, thanks for developing such a useful tool! 

I would like to ask whether CAUSE results for traits with low heritability (h2 ~0.02) would still be reliable or whether you recommend applying this method only to traits with higher heritability. I saw that the simulations run for the paper assume h2=0.25, but I wondered whether you have explored traits with lower heritability.

Many thanks in advance!

Best wishes,
María

**Comment by jean997** [comment]
Hi María,
We have never implemented a heritability filter. I can't think of a reason that the method would perform badly with low heritability traits (though power will be reduced if effect sizes are small and GWAS sample size is low). I haven't run simulations with lower heritability. We have applied CAUSE to real data with a range of heritabilities and not had problems (at least that I was aware of).
Jean
