### ISSUE TITLE
Error: Not all `variants` are in data.

### ISSUE THREAD

**Issue by bbb801** [jean997/cause#24]
![image](https://user-images.githubusercontent.com/52306405/144093650-b537a58d-5556-4005-a8cb-e4981ee8bc2e.png)
Hi, When I run your pipeline, I got the error' Not all `variants` are in data.' Any suggestion?
By the way, is it workable to use your pipeline to run on my own summary data? 
Thank you!

#########################################################
Warning message:
One or more parsing issues, see `problems()` for details 
Error: Not all `variants` are in data.
Execution halted
[Wed Dec  1 00:54:56 2021]
Error in rule cause:
    jobid: 61
    output: results/tagc_asthma__glg_ldl_cause_1_100.RDS
    shell:
        Rscript R/cause.R data/tagc_asthma__glg_ldl_data.RDS data/snps_tagc_asthma__glg_ldl.plink.pruned.txt results/tagc_asthma__glg_ldl_params.RDS                    1 100 1                    results/tagc_asthma__glg_ldl_cause_1_100.RDS 100
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by jean997** [comment]
It's a little hard to tell from this output but you will get this error if there is a line in `data/snps_tagc_asthma_glgl_ldl.plink.pruned.txt` that is not a name of a SNP in `data/tagc_asthma_ldl_data.RDS`. This shouldn't be possible if both files were produced using the pipeline so it looks like you found a bug. Try doing this:

```
library(readr)
snps <- read_lines("data/snps_tagc_asthma_glgl_ldl.plink.pruned.txt")
dat <- readRDS("data/tagc_asthma_ldl_data.RDS")
all(snps %in% dat$snp) # I think you should get FALSE here based on your error

dim(dat)
head(dat)

length(snps)
snps[!snps %in% dat$snp]
``` 

If you share the output of this, that will help me find the problem.

**Comment by jean997** [comment]
Thanks, I think I found the error. If you re-run `cause_setup_pipeline()` it should download the fixed version. Alternatively, you can just replace the file `R/ld_prune_plink.R` with https://github.com/jean997/cause/blob/master/pipeline_code/R/ld_prune_plink.R.

**Comment by bbb801** [comment]
Thank you! It is workable. It seems there is a warning of the conflict about the 'dplyr' package. May I know if I could use my own datasets and how to cite this pipeline?

**Comment by jean997** [comment]
Yes feel free to use and modify the pipeline as you see fit. Thanks for citing it. If you update it in a way you think would be useful to others feel free to submit a pull request.
