### ISSUE TITLE
LCV error in pipeline

### ISSUE THREAD

**Issue by bbb801** [jean997/cause#25]
Dear Sir/Madam,

When I used my own data to run the pipe, I got an error: Error in causeSims::RunLCV(L2, beta_hat_1/seb1, beta_hat_2/seb2, no.blocks = 100,  : NaNs produced, probably due to negative heritability estimates. Check that summary statistics and LD scores are ordered correctly.

Could you provide some suggestions?

#################################################################
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error in causeSims::RunLCV(L2, beta_hat_1/seb1, beta_hat_2/seb2, no.blocks = 100,  : 
  NaNs produced, probably due to negative heritability estimates. Check that summary statistics and LD scores are ordered correctly.
Calls: with -> with.default -> eval -> eval -> <Anonymous>
In addition: Warning messages:
1: In sqrt(h2g.1 * h2g.2) : NaNs produced
2: In sqrt(WeightedMean(z.1^2, weights) - intercept.1) : NaNs produced
Execution halted
[Tue Dec  7 14:56:46 2021]
Error in rule lcv:
    jobid: 37
    output: results/nih__ih_lcv.RDS
    shell:
        Rscript R/lcv.R data/nih__ih_data.RDS  ld_scores/eur_w_ld_chr/ results/nih__ih_lcv.RDS
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!) 

![image](https://user-images.githubusercontent.com/52306405/144981900-af3fd932-6a68-4259-a69b-0d804c6b3b88.png)

**Comment by jean997** [comment]
This error is coming from LCV and the error message is probably informative. LCV can't run if the LD score heritability point estimates are negative which can happen when the heritability is low or the variance of the estimate is high. You can try running LD score regression on your data and see if that is the case.
