### ISSUE TITLE
LD pruning 

### ISSUE THREAD

**Issue by Rick-Chen-PKU** [jean997/cause#27]
As shown in the figure below, about **6905720** variants are obtained through the **gwas_merge** function. Then I pruning with the parameter **pval_thresh = 1e-5** and it turns out that there is an error in the **api_query** i.e. "**_The query to MR-Base exceeded 300 seconds and timed out. Please simplify the query_**". Is there any way to solve this problem? Can I randomly reduce my variants? Any solution to this problem is very apprecited. Thanks!

![7f1059718e1b429edf6a35d7d335a61](https://user-images.githubusercontent.com/52855963/167471335-478eaf05-1f0c-415d-98bb-f0be65707d7c.png)

**Comment by jean997** [comment]
Yes - you can store the LD files locally which I think will help. Try looking here for how to do it
https://mrcieu.github.io/ieugwasr/articles/local_ld.html
