### ISSUE TITLE
gwas_merge error with pval_cols

### ISSUE THREAD

**Issue by jdjmoon** [jean997/cause#29]
Hello,

As I was running the example, I have encountered an issue when I was trying to run the example. The error I have obtained was Error in gwas_merge with pval_cols.

I looked at the closed issue and tried both release and development version (1.2.0.0335). I have also tried deleting packages from r and reinstalled development version but still getting same error.

Is there anyway to solve it? Thank you.

**Comment by jean997** [comment]
Can you post your `sessionInfo()` and the error message you get?

**Comment by jdjmoon** [comment]
Hello, I have actually removed R and tried redownloading and appears to be working. I think the error occurred due to my environment. Thank you.
