### ISSUE TITLE
decimal places

### ISSUE THREAD

**Issue by rheuzhas** [jean997/cause#31]
Dear Jean, *not an issue per se* is there a way to increase the number of decimal places for gamma, eta, etc? e.g., gamma 0.01, 95%CrI 0.01 0.02, reporting gamma as estimate of the causal effect would benefit from CrI. Many thanks for this great method.

**Comment by jean997** [comment]
Yes you can increase the digits argument in the summary function
```
summary(res, digits = 10)
```
