### ISSUE TITLE
The 95% CI of gamma does not contain 0 while the P-value for the comparison between the sharing model and causal model exceeds 0.05

### ISSUE THREAD

**Issue by Steven-ZWQ** [jean997/cause#32]
Hi Jean,
Now I'm performing a CAUSE analysis, but I'm unsure how to explain the result.
The 95% CI of gamma does not contain 0 while the P-value for the comparison between the sharing model and causal model exceeds 0.05. For example, gamma equals -0.074 (-0.135 - -0.018), while the z-score is -0.696 corresponding to a p-value of 0.243. 
Is there a causal effect of M on Y and a shared factor between M and Y?

Thank you,
Wenqiang.

**Comment by jean997** [comment]
Hi Wenqiang,
The CI is a credible interval and isn't directly linked with the p-value (which is testing whether the posteriors under the causal model describe the data better than the posteriors under the non-causal model) so it's not impossible to see what you are seeing. However, it is surprising, I haven't come across this type of result before. It would help to know more about your results and analysis. Can you share these details: 
- How many variants did you use in the second stage to estimate the posteriors? What p-value threshold did you use to choose these?
- Can you post the full table of results and the plots of the posterior distributions?

Jean

**Comment by Steven-ZWQ** [comment]
Hi Jean,
LD pruned at r2 < 0.1 with P < 1 × 10−3 as you recommended, and 4914 variants were used to estimate CAUSE posteriors.
![1CAUSE](https://user-images.githubusercontent.com/60351256/207747989-158f9040-1c53-429a-b2a7-4b3bdd6a8d75.PNG)
![causal model](https://user-images.githubusercontent.com/60351256/207748003-5436750e-d667-42d6-9c75-9389be0fb292.PNG)
![sharing model](https://user-images.githubusercontent.com/60351256/207748128-36b2687d-2646-4dab-b7ff-b60d1638202d.PNG)

**Comment by jean997** [comment]
Great thanks. To me, the thing that jumps out to me is that in the causal model the posterior distribution of eta is bimodal. It may be that the posterior of gamma is also bimodal, though you would need to change the scale of the x-axis to see. It could be that the data would be better fit by a mixture model with more than two parts (e.g. more than one latent factor). The other thing I notice is that in the sharing model, the posterior of q is high but not very high. 

From these results, I would conclude that CAUSE doesn't find strong evidence in favor of the causal model compared to the sharing model.  However, it is worth noting that this is a conservative answer. CAUSE didn't reject the causal model, in fact the posteriors for the causal model predict a little better than the posteriors of the sharing model, just not so much better that the sharing model can be rejected using this test. In short, CAUSE is equivocal. 

The bimodal distribution of eta also suggests that there is a substantial amount of heterogeneity in the data which could be worth further exploring. You can get an idea of the heterogeneity by plotting the scatter plot option and by computing the Cochran's Q statistic. If you can understand any of the source of the hetergeneity (e.g. known heritable confounders), this can also help.

Jean

**Comment by Steven-ZWQ** [comment]
Thanks so much.

Wenqiang!

**Comment by DongshengWu** [comment]
Hi Wenqiang,
I encountered a similar issue as you did. Could you please share how you ultimately resolved this problem?
