### ISSUE TITLE
CAUSE's results

### ISSUE THREAD

**Issue by giuliapontali** [jean997/cause#38]
Hi,

I am trying to compare the results obtained with `cause` and the ones obtained with the classical Mendelian randomization approach.
Can you better explain the meaning of the models in `res$elpd` results? 

- the `null model` means no pleiotropy and no causality?
- the `causal model` means causal effect and no pleiotropy?
- the `sharing model` means no causal effect and yes pleiotropy?

How can we define the best model?

And also, If I run CAUSE without doing the clumping step I obtained that model 1 is better than model 2. Do you think that these results have sense?

Thanks a lot for the clarity.

**Comment by jean997** [comment]
yes your interpretations are correct. I encourage you to check out the description here
https://jean997.github.io/cause/ldl_cad.html#Step_5:_Look_at_Results
The best fitting model is the model with the highest elpd. The z-score tells you if the difference in elpd between the two models is significant. If we use the results in the link above as an example, delta_elpd is negative on every row. This means that the elpd for the sharing model is higher than the elpd for the null model and the elpd for the causal model is higher than the elpd for the sharing model. So the causal model has the highest elpd. We can also look at the z-score and conclude that the causal model is significantly better than the sharing model. 

CAUSE requires independent variants so you should not run it without clumping.

**Comment by giuliapontali** [comment]
Thank you.

Can you just confirm if the `causal model` means causality and no pleiotropy? Or causality and yes pleiotropy?
Is it possible to extract the` elpd ` for each model?

I also have another question about the results. Why doing `summary(res, ci_size=0.95)` I get:
 ```
       Length Class          Mode
sharing  8     cause_post     list
causal    8     cause_post     list
elpd      5     cause_elpd     list
loos      3     -none-         list
data    13     cause_data_fit list
sigma_g  1     -none-         numeric
qalpha   1     -none-         numeric
qbeta    1     -none-         numeric
```

Thanks
