### ISSUE TITLE
CAUSE's results #38

### ISSUE THREAD

**Issue by giuliapontali** [jean997/cause#41]
Can you just confirm if the `causal model` means causality and no pleiotropy? Or causality and yes pleiotropy?
Is it possible to extract the` elpd ` for each model?

I also have another question about the results. Why doing `summary(res, ci_size=0.95)` I get:
 ```
       Length Class          Mode
sharing  8     cause_post     list
causal    8     cause_post     list
elpd      5     cause_elpd     list
loos      3     -none-         list
data    13     cause_data_fit list
sigma_g  1     -none-         numeric
qalpha   1     -none-         numeric
qbeta    1     -none-         numeric
```

Thanks

_Originally posted by @giuliapontali in https://github.com/jean997/cause/issues/38#issuecomment-1625285750_

**Comment by jean997** [comment]
The causal model includes a causal effect and allows for a confounder. CAUSE doesn't try to test if there is a confounder or not. I left a longer comment about this on your other issue.

The `elpd` is stored in `res$elpd`
(see https://jean997.github.io/cause/ldl_cad.html#Step_5:_Look_at_Results)

It sounds like you don't have the `cause` package loaded when you run the summary command. Try making sure the library is loaded first.
