### ISSUE TITLE
OR and CI

### ISSUE THREAD

**Issue by frucelee** [jean997/cause#43]
Hi,

Thanks a lot for the packages. I am new to the software. Sorry, just a very naive question. How can we obtain the odd ratio and 95% CI estimation of causal effect using this software?

Best,

Lee

**Comment by jean997** [comment]
Hi Lee,
I would recommend going through the example here:
https://jean997.github.io/cause/ldl_cad.html
 and looking through the paper. 

CAUSE produces credible intervals rather than confidence intervals because it is a Bayesian method. These can be produced with the built in summary() function.
