### ISSUE TITLE
 Does this indicate a lack of causal relationship?

### ISSUE THREAD

**Issue by f174937** [jean997/cause#45]
I have a question regarding the results I obtained using your methodology. The p-value for the CAUSE model exceeds 0.05. Does this indicate a lack of causal relationship?

model1  model2 delta_elpd se_delta_elpd          z
--
1    null sharing  0.2030073     0.1568134  1.2945782
2    null  causal -0.9606224     1.2914358 -0.7438406
3 sharing  causal -1.1636296     1.1884105 -0.9791479
p-value testing that causal model is a better fit:  0.16
Posterior medians and  95 % credible intervals:
model     gamma            eta                   q
[1,] "Sharing" NA               "0.04 (-0.52, 0.49)"  "0.05 (0, 0.27)"
[2,] "Causal"  "0.04 (0, 0.08)" "-0.02 (-0.56, 0.49)" "0.04 (0, 0.24)"

**Comment by jean997** [comment]
I think this case is a little borderline personally. I think it is ok to make inference based on the 95\% credible interval for gamma, though in the paper we use the model comparison p-value. The model comparison p-value is more conservative. Basically this is telling you that when you fit the model with a causal effect, most of the posterior is positive. The causal model also fits better than the non-causal (sharing only model). However, the causal model doesn't fit overwhelmingly better than the sharing model. So I think this is weak evidence of a causal effect.

**Comment by yu137178** [comment]
Hi jean
I also meet similar questions.Although the p-value is not significant，but my result plot are similar to plot from  Example Analysis with CAUSE https://jean997.github.io/cause/ldl_cad.html#Step_5:_Look_at_Results.My code are listed as follows.

> res <- cause(X=X, variants = top_vars, param_ests = params)
Estimating CAUSE posteriors using  2381  variants.
Fitting confounder only model.
Setting ranges
Refining grid
Fitting causal model.
Setting ranges
Refining grid
> res$elpd
   model1  model2 delta_elpd se_delta_elpd         z
1    null sharing  -3.963407      2.020211 -1.961878
2    null  causal  -7.006506      3.898137 -1.797398
3 sharing  causal  -3.043099      1.946208 -1.563604
> summary(res, ci_size=0.95)
p-value testing that causal model is a better fit:  0.059 
Posterior medians and  95 % credible intervals:
     model     gamma               eta                   q                  
[1,] "Sharing" NA                  "1.34 (0.39, 2.85)"   "0.22 (0.02, 0.46)"
[2,] "Causal"  "0.56 (0.25, 0.88)" "-0.35 (-6.11, 4.72)" "0.03 (0, 0.24)"   
> plot(res)

![5084104156d5efa49ae939cc75f4980](https://github.com/user-attachments/assets/05ef5382-23ac-4b23-8823-da2758748357)

Yours sincerely,
 Chongyang Yu

**Comment by jean997** [comment]
I would give the same comment here as above. You have two choices about inference. You could use a local false sign rate which would be the level at which the credible interval for gamma hits zero or you can use the elpd p-value. These are assessing different hypotheses in terms of the model. The LFSR tells you, given that you believe the causal model, what is the probability that you have estimated the sign of the causal effect correctly. The elpd tests which of the two models fits the data best.

**Comment by jean997** [comment]
Chongyang - I would guess that there is a lot of heterogeneity in your data given that the sharing model fits well. You may look at the instrument plot to see if this is the case.
