### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by 931902655** [jean997/cause#47]
Hi jean!
I encountered this problem after running
 ```
X_clump <- X %>%
  rename(rsid = snp,
         pval = p1) %>%
  ieugwasr::ld_clump(dat = .,
                     clump_r2 = r2_thresh,
                     clump_p = pval_thresh,
                     plink_bin = "/usr/local/lib/R/site-library/plinkbinr/bin/plink_Linux", 
                     bfile = "/home/vee/code/pakage/EUR/EUR")
```
the following pic is the error
![2b9119749f0178652a79bd731695fed](https://github.com/jean997/cause/assets/24243685/dde1c340-1d91-4fd0-80e2-2196ee2957dc)
Can you tell me how solve this problem?
Thank you very much.
Best regards.

**Comment by jean997** [comment]
your error is coming from the ieugwasr package and not the CAUSE package so you should post this there: 
https://github.com/mrcieu/ieugwasr/

All I can tell you is that ld clumping failed. I would start by checking these things:
+ The bim/bed/fam files are where you think they are
+ The plink binary is where you think it is
+ your data is formatted correctly. 

Look at the examples in the ieugwasr documentation and if you are still getting errors, post an issue on the ieugwasr issues page.
